### PR TITLE
Add three examples for date-time operations

### PR DESCRIPTION
**Pull request by jjcipher**
1. to find out the differences between two given dates;
2. to find out how many days of the given month;
3. to find out how many days of the given year.

### CODE REVIEW

**Comment by jacksu** [comment]
好像你的项目，build错误

**Comment by jacksu** [comment]
是否还有什么没有提交呢？

**Comment by jjcipher** [comment]
I am sorry!  Please reject my pull request for now.  I will check that when
I get back home.

**Comment by jacksu** [comment]
I am sorry,I am wrong.You are right.I merged,thanks.

**Pull request merged**
